"use client";

import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Mail, MapPin, MessageCircle, Phone, ShieldCheck, ShoppingBag, Sparkles, Target } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { api } from "@/lib/api";
import { money } from "@/lib/utils";
import { Badge, Card, ErrorState, Loading } from "@/components/ui";

type Profile = { firstName: string; lastName: string; email: string; phone?: string; city?: string; status: string; preferredChannel: string; totalSpend: string; orderCount: number; loyaltyScore: number; fatigueScore: number; opportunityScore: number; scoreExplanation?: { opportunity?: string; fatigue?: string }; orders: Array<{ id: string; orderNumber: string; total: string; status: string; orderedAt: string }>; communications: Array<{ id: string; status: string; channel: string; createdAt: string; campaign: { name: string }; events: Array<{ id: string; type: string; occurredAt: string }> }> };

export default function ShopperProfile() {
  const { id } = useParams<{ id: string }>();
  const query = useQuery({ queryKey: ["shopper", id], queryFn: () => api<Profile>(`/customers/${id}`) });
  if (query.isLoading) return <Loading />;
  if (query.isError || !query.data) return <ErrorState message={query.error?.message ?? "Unknown error"} />;
  const shopper = query.data;
  return <div className="mx-auto max-w-7xl px-5 py-8 md:px-9">
    <Link href="/shoppers" className="flex items-center gap-1.5 text-xs text-black/45 hover:text-black"><ArrowLeft size={14} /> All shoppers</Link>
    <div className="mt-6 flex flex-col justify-between gap-5 md:flex-row md:items-start"><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-[#e8e4ff] text-lg font-semibold text-violet">{shopper.firstName[0]}{shopper.lastName[0]}</div><div><div className="flex items-center gap-2"><h1 className="text-2xl font-semibold tracking-tight">{shopper.firstName} {shopper.lastName}</h1><Badge tone={shopper.status === "ACTIVE" ? "green" : "neutral"}>{shopper.status}</Badge></div><div className="mt-2 flex flex-wrap gap-4 text-xs text-black/40"><span className="flex items-center gap-1"><Mail size={12} />{shopper.email}</span>{shopper.phone && <span className="flex items-center gap-1"><Phone size={12} />{shopper.phone}</span>}<span className="flex items-center gap-1"><MapPin size={12} />{shopper.city}</span></div></div></div><button className="rounded-xl bg-ink px-4 py-2.5 text-xs font-medium text-white">Ask Genie about shopper</button></div>
    <div className="mt-7 grid gap-4 md:grid-cols-4">{[{ label: "Lifetime value", value: money(Number(shopper.totalSpend)), icon: ShoppingBag }, { label: "Loyalty score", value: shopper.loyaltyScore, icon: ShieldCheck }, { label: "Opportunity", value: shopper.opportunityScore, icon: Target }, { label: "Fatigue", value: shopper.fatigueScore, icon: MessageCircle }].map((item) => <Card key={item.label} className="p-5"><div className="flex items-center justify-between text-xs text-black/40"><span>{item.label}</span><item.icon size={15} /></div><p className="mt-4 text-2xl font-semibold">{item.value}</p></Card>)}</div>
    <div className="mt-4 grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-4"><Card className="p-5"><div className="flex items-center gap-2"><Sparkles size={16} className="text-violet" /><h2 className="font-semibold">Why Genie scored this shopper</h2></div><div className="mt-5 space-y-4"><Reason title="Purchase opportunity" value={shopper.opportunityScore} text={shopper.scoreExplanation?.opportunity ?? "Calculated from recency, frequency, value, and engagement."} /><Reason title="Communication fatigue" value={shopper.fatigueScore} text={shopper.scoreExplanation?.fatigue ?? "Calculated from communication volume and response patterns."} /></div><div className="mt-5 rounded-xl bg-[#f6f4ff] p-3 text-xs leading-5 text-black/55">Preferred channel: <strong className="capitalize text-black">{shopper.preferredChannel.toLowerCase()}</strong>. Genie uses this only when fatigue policy allows contact.</div></Card><Card className="p-5"><h2 className="font-semibold">Recent orders</h2><div className="mt-3 divide-y divide-black/[0.05]">{shopper.orders.slice(0, 6).map((order) => <div key={order.id} className="flex items-center justify-between py-3"><div><p className="text-xs font-medium">{order.orderNumber}</p><p className="mt-0.5 text-[11px] text-black/35">{new Date(order.orderedAt).toLocaleDateString()}</p></div><div className="text-right"><p className="text-sm font-medium">{money(Number(order.total))}</p><p className="text-[10px] text-black/35">{order.status}</p></div></div>)}</div></Card></div><Card className="p-5"><h2 className="font-semibold">Relationship timeline</h2><p className="mt-1 text-xs text-black/40">Campaign touches and engagement events.</p><div className="relative mt-6 space-y-6 before:absolute before:bottom-2 before:left-[7px] before:top-2 before:w-px before:bg-black/[0.08]">{shopper.communications.slice(0, 10).map((communication) => <div key={communication.id} className="relative flex gap-4"><span className="z-[1] mt-1 h-[15px] w-[15px] shrink-0 rounded-full border-4 border-white bg-violet shadow-sm" /><div className="flex-1 border-b border-black/[0.04] pb-5"><div className="flex justify-between gap-4"><div><p className="text-sm font-medium">{communication.campaign.name}</p><p className="mt-1 text-xs text-black/40">{communication.channel} · {communication.status}</p></div><span className="text-[10px] text-black/30">{new Date(communication.createdAt).toLocaleDateString()}</span></div>{communication.events.length > 0 && <div className="mt-3 flex flex-wrap gap-1.5">{communication.events.slice(0, 5).map((event) => <Badge key={event.id} tone={event.type === "PURCHASED" ? "green" : "neutral"}>{event.type}</Badge>)}</div>}</div></div>)}</div></Card></div>
  </div>;
}

function Reason({ title, value, text }: { title: string; value: number; text: string }) {
  return <div><div className="flex justify-between text-xs"><span className="font-medium">{title}</span><strong>{value}/100</strong></div><div className="mt-2 h-1.5 rounded-full bg-black/[0.05]"><div className="h-full rounded-full bg-violet" style={{ width: `${value}%` }} /></div><p className="mt-2 text-xs leading-5 text-black/45">{text}</p></div>;
}

